# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dilidili-client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dilidili-client
#    pod 'MiniTabBar', '~> 1.1.0'
#    pod 'RAMAnimatedTabBarController', '3.0.4'
    pod 'Alamofire', '~> 4.7.2'
    pod 'SwiftyJSON', '~> 4.1.0'

  target 'dilidili-clientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dilidili-clientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
