# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dilidili-client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dilidili-client
  pod 'Alamofire', '~> 4.7.2'#网络请求框架
  pod 'SwiftyJSON', '~> 4.1.0'#json解析框架
  pod 'BMPlayer', '~> 1.0.0'#视频播放器框架
  target 'dilidili-clientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dilidili-clientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
